apiVersion: v1
entries:
  golang-echo-graphql-example:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-07-01T22:55:40.38853+03:00"
    description: A Helm chart for deploying Golang Echo Graphql Example
    digest: 5ce36c28ade20e0fcbcfe21cc3467c8542ea74d7813a41474ae863c54ae54f7c
    name: golang-echo-graphql-example
    type: application
    urls:
    - golang-echo-graphql-example-1.0.0.tgz
    version: 1.0.0
generated: "2021-07-01T22:55:40.38592+03:00"
